
package movie.managementWS.web.service.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 2.7.18
 * Sun Apr 11 17:33:38 CEST 2021
 * Generated source version: 2.7.18
 */

@XmlRootElement(name = "addMovie", namespace = "http://service/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "addMovie", namespace = "http://service/")

public class AddMovie {

    @XmlElement(name = "arg0")
    private movie.managementWS.web.data.Movie arg0;

    public movie.managementWS.web.data.Movie getArg0() {
        return this.arg0;
    }

    public void setArg0(movie.managementWS.web.data.Movie newArg0)  {
        this.arg0 = newArg0;
    }

}

